### ISSUE TITLE
Migrate to using Nes for Websockets

### ISSUE THREAD

**Issue by nelsonic** [dwyl/api#14]
- https://github.com/hapijs/nes
- https://github.com/hapijs/nes/blob/master/API.md
- https://github.com/hapijs/nes/blob/master/PROTOCOL.md

**Comment by iteles** [comment]
The question here is why?

This is an excellent reminder that I've been terrible and completely forgot about the `nes` issue we were discussing https://github.com/dwyl/hapi-socketio-redis-chat-example/issues/41 (desculpa @sericaia!)

@sericaia has done some excellent work in starting to compare socket.io and nes:
Simple chat with `socket.io`: https://github.com/sericaia/socketio-hapi-chat      
Simple chat with `nes`: https://github.com/sericaia/nes-chat

She's used [thor](https://github.com/observing/thor) for looking at `nes` ([results here](https://gist.github.com/sericaia/fe7c9937f3bff35b6460) but hasn't replicated this for `socket.io` yet.

**Comment by nelsonic** [comment]
Superceeded by using Phoenix Channels.
