### ISSUE TITLE
allow + (plus) symbol in email addresses for prefixes?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/api#4]
Mandril is ignoring the plus symbol.
which means people cannot use prefixes in gmail...

![mandril-ignores-plus-symbol](https://cloud.githubusercontent.com/assets/194400/8264144/9a1258be-16da-11e5-80d7-86ad6f06de0a.png)

@iteles do you agree that this is required?

related to: https://github.com/dwyl/api/issues/3

**Comment by iteles** [comment]
I don't think it's a deal breaker, but it would be very nice to have that option. The smoother we can make the sign up process the better.

**Comment by nelsonic** [comment]
Done.

**Comment by iteles** [comment]
:+1: :+1:
