### ISSUE TITLE
Re-word welcome email?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/api#5]
![dwyl-welcome-email](https://cloud.githubusercontent.com/assets/194400/8264261/e308c4ee-16db-11e5-88d7-f04e9e41e494.png)

**Comment by nelsonic** [comment]
See: https://github.com/dwyl/api/blob/23fbae4bd030d4b1099f0f850f078f8dcfba55c1/email_templates/welcome_html.html

**Comment by iteles** [comment]
Absolutely. We'll need different welcome emails depending on whether people are signing up through the app or through the website.
At the moment it's people signing up though the website so needs to be changed asap!

**Comment by nelsonic** [comment]
Please re-word and PR!

**Comment by iteles** [comment]
@nelsonic  **How does this sound for now? We'll change this almost weekly I imagine once the [summer of code](https://github.com/dwyl/summer-2015) gets started.**

Hi!

Welcome to dwyl! Thanks so much for your interest, we're excited to have you!

At dwyl we work to help you do what you love (whether you know what that is yet or not). We do this through technology and we hold certain beliefs strongly, including that *your data belongs to you* and no one else. You can see those here: href="https://github.com/ideaq/start-here/blob/master/manifesto.md

As we develop dwyl, you'll be the first to hear of the progress and the first to use the app.

If you have any questions or suggestions, please reply to this email or add an issue to github here (if that's your kind of thing): https://github.com/dwyl/time/labels/MVP
We really appreciate it!

Happy dwyling,
Ines & Nelson

**Comment by nelsonic** [comment]
Reads well. I would use http://git.io/ links to make them shorter. But that will change in the next week in any case so, just ship it!

**Comment by iteles** [comment]
Good shout on git.io.

Also, yes! I'll figure it out for sure ;)

**Comment by iteles** [comment]
http://blog.getvero.com/welcome-emails/
http://www.verticalresponse.com/blog/10-examples-of-highly-effective-welcome-emails/

**Comment by iteles** [comment]
**git.io shortening:**   
Argh, forgot to link in commit message https://github.com/dwyl/api/commit/f14cb0b940f4d1d5a668b809d053cd042d7f00e0

It's one to reconsider when we change the email next time as it might be nice for people to see upfront where they're being taken to - i.e. that the 'beliefs' bit points to a 'manifesto.md' file for example.

**Comment by iteles** [comment]
![deployed-new-welcome-email-to-heroku-api](https://cloud.githubusercontent.com/assets/4185328/8358184/da52976a-1b56-11e5-9a67-e8d64c8e7b9a.jpg)

**Comment by nelsonic** [comment]
I love how you think your email address is hard to guess... :laughing:

**Comment by iteles** [comment]
pinkfluffyunicorns83@gmail.com? I thought it wasn't that obvious!

**Comment by nelsonic** [comment]
and now everyone knows you're year of birth... you're a fan of leaking info... :smile_cat:

**Comment by iteles** [comment]
Just terrible.

**Comment by nelsonic** [comment]
https://www.youtube.com/watch?v=a-xWhG4UU_Y
