### ISSUE TITLE
custom domain for api.dwyl.io ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/api#8]
I feel we should add a custom domain to make https://dwylapi.herokuapp.com/ https://api.dwyl.io

What do you think? (there's no cash cost, just time to set it up)

see: https://devcenter.heroku.com/articles/custom-domains

I've added you as colab so you can do it:

![dwyl-api-access-granted-to-ines](https://cloud.githubusercontent.com/assets/194400/8266276/1a04f606-171e-11e5-8e60-84595cb4b370.png)

**Comment by iteles** [comment]
I totally agree. We should base everything off our own domain. I'm on it.

**Comment by iteles** [comment]
Changed in Domain provider:
![domain-provider-DNS-change](https://cloud.githubusercontent.com/assets/4185328/8359489/a52342a8-1b5e-11e5-95ca-683ad39d18c9.png)

Changed in Heroku:
![heroku-changes](https://cloud.githubusercontent.com/assets/4185328/8359490/a5238e2a-1b5e-11e5-85a0-30f068f54cc9.png)

Fully working:
![working-in-heroku](https://cloud.githubusercontent.com/assets/4185328/8359488/a515738a-1b5e-11e5-9501-a22d26782057.png)

**Comment by iteles** [comment]
![heroku remote](https://cloud.githubusercontent.com/assets/4185328/8380179/513ad458-1c1c-11e5-9ec4-a279861da254.png)

**Comment by nelsonic** [comment]
:boom:
